### ISSUE TITLE
Lots of errors after upgrading Flow past v0.82: "Cannot use function type as a type because function type is a value."

### ISSUE THREAD

**Issue by callumlocke** [flow-typed/flow-typed#2909] opened 2018-10-26 10:55 UTC
I just upgraded from Flow v0.81 to v0.84, and it's now reporting lots of errors in flow-typed libdefs:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ flow-typed/npm/ramda_v0.x.x.js:1521:59

Cannot use function type as a type because function type is a value. To get the type of a value use typeof.

     1518│     (<S: string, A: { [k: string]: T }, B: { [k: string]: T }, T>(
     1519│       fn: (s: S, a: T, b: T) => T,
     1520│     ) => (a: A) => (b: B) => A & B) &
     1521│     (<S: string, A: { [k: string]: T }, B: { [k: string]: T }, T>(
     1522│       fn: (s: S, a: T, b: T) => T,
     1523│       a: A,
     1524│     ) => (b: B) => A & B);
```

I'm guessing this is due to this [breaking change in Flow v0.82](https://github.com/facebook/flow/releases/tag/v0.82.0):

> Likely to cause new Flow errors:
> - Removed the ability to use functions as type annotations. This ability was
originally designed to support ES3-style classes, but in practice causes
confusion and missed errors. We found that the vast majority of added errors
were detecting legitimate bugs, and the remainder could be easily updated to
ES6 classes.

Is there some quick way we can fix all these kinds of errors in a batch? Or at least just rename all these libdefs to mark them as only valid up to v0.81?

**Comment by pascalduez** [comment] 2018-10-27 01:05
@callumlocke could you list the lib defs you use. We could then start patching them one by one. 
Maybe some are fixed in #2861

**Comment by villesau** [comment] 2018-11-07 21:48
@callumlocke there went now big bunch of regression fixes in. Did they solve your issues? :)

**Comment by AndrewSouthpaw** [comment] 2019-02-14 20:54
Clsoing because we can't repro and OP hasn't responded.

**Closed by AndrewSouthpaw** 2019-02-14 20:54 UTC
