### ISSUE TITLE
lodash flow validation fails

### ISSUE THREAD

**Issue by ycharniauski** [flow-typed/flow-typed#3473] opened 2019-07-25 12:42 UTC
Flow validation fails
![image](https://user-images.githubusercontent.com/22836933/61874882-20f8b680-aef2-11e9-8c88-ad0c6079cbf2.png)

![image](https://user-images.githubusercontent.com/22836933/61875068-86e53e00-aef2-11e9-8074-fec0214db82a.png)

This commit brokes it:
https://github.com/flow-typed/flow-typed/commit/f125eacb942c4cc495330643a890c97ed6cc460d

Hope it will be fixed soon, cause right now we are using previous stable version, in our project.
Thanks

**Comment by pascalduez** [comment] 2019-07-25 12:46
Dupe of  #3463

**Closed by pascalduez** 2019-07-25 12:46 UTC

**Comment by JavierLaguna** [comment] 2019-07-25 13:04
I have the same issue

**Comment by AndrewSouthpaw** [comment] 2019-07-29 02:00
Would someone be willing to put in a test to prevent this issue from happening in the future?
