### ISSUE TITLE
How to create a libdef for something that extend's Jest's 'expect' global?

### ISSUE THREAD

**Issue by callumlocke** [flow-typed/flow-typed#2054] opened 2018-04-07 15:10 UTC
Jest provides [`expect.extend`](https://facebook.github.io/jest/docs/en/expect.html#expectextendmatchers), which lets you add custom extensions to its `expect` global.

A library called [expect-puppeteer](https://github.com/smooth-code/jest-puppeteer/tree/master/packages/expect-puppeteer) uses this feature to add new assertions useful for integration testing with Puppeteer, like `expect(page).toClick(...)`.

But this causes Flow to complain that `.toClick` is not a thing. Flow knows the return value of `expect()` is a [`JestExpectType`](https://github.com/flowtype/flow-typed/blob/bc9a27af0937034eddd1d979cd6bf5175e6acede/cli/flow-typed/npm/jest_v22.x.x.js#L144-L286) object (because of the Jest libdef), which means you can do things like `expect(x).toBeDefined()` and Flow understands it. But any custom extensions don't work.

So I want to write a new libdef for expect-puppeteer (or possibly its parent jest-puppeteer) that somehow augments the `expect` global that's originally declared by the Jest libdef.

Is this possible? If the same global (`expect`) is declared in two different libdefs, is there some way to merge them? Or would I need to redeclare everything that already gets declared by the Jest libdef?

**Comment by AndrewSouthpaw** [comment] 2018-04-11 23:33
I thiiiink you would need to do something like `import expect from 'expect-puppeteer'` in order to pull the types from the correct libdef. Would love to hear the opinions of others.

**Comment by AndrewSouthpaw** [comment] 2018-04-13 18:59
When you're doing so, [note this nuance](https://github.com/flowtype/flow-typed/issues/1857#issuecomment-371312890).

**Comment by callumlocke** [comment] 2018-04-14 08:49
The [enzyme](https://github.com/airbnb/enzyme/) plugin does the same thing (augmenting the global `expect`), and I've just noticed something.

The enzyme type definitions are simply [bundled into the Jest definition](https://github.com/flowtype/flow-typed/blob/aba577ee638172d7f0b2d0e7a79fee060459c440/definitions/npm/jest_v22.x.x/flow_v0.39.x-/jest_v22.x.x.js#L572) (along with those of another plugin I haven't heard of called [dom-testing-library](https://github.com/kentcdodds/dom-testing-library#custom-jest-matchers)).

Are flow-typed maintainers aware of this pattern? The downsides I can see are:

- These plugin-added types will apply to anyone using Jest, even people who don't use these plugins. So their Flow autocomplete will suggest things they can't use.
- Two plugins might add expectation methods with the same name but clashing type signatures.
- This pattern makes some plugins 'first class' without any clear criteria

**Comment by AndrewSouthpaw** [comment] 2018-05-02 06:52
Hmm... well, I don't have much context around it, but I guess it makes sense. I agree with your downsides, and as long as we can avoid the clashes we'll prooooobably be alright? I'd say make the change, see if any tests blow up, if they don't, merge, and see if anyone complains. 😉

**Comment by pascalduez** [comment] 2019-08-15 11:03
Dupe of #948

**Closed by pascalduez** 2019-08-15 11:03 UTC
Labels: libdef, question
