### ISSUE TITLE
[lodash v4.x.x] keyBy should return a map of maybe types

### ISSUE THREAD

**Issue by ampersandre** [flow-typed/flow-typed#2654] opened 2018-08-22 17:11 UTC
In https://github.com/flow-typed/flow-typed/pull/2641, the response type of lodash's `keyBy` was changed from
`{ [key: V]: ?T }`
to
`{ [key: V]: T }`

I believe this is incorrect, and should be reverted.

The object returned by `keyBy` cannot guarantee a value for every key.

Example:
```
const map = lodash.keyBy([{ id: 1 }, { id: 2 }, { id: 3}], e => e.id);
map[1] // { id: 1 }
map[2] // { id: 2 }
map[7] // undefined
```

**Comment by wchargin** [comment] 2018-08-23 01:08
Subscript access on objects with an indexer property is [unchecked by
design.][docs] You can [easily reproduce this without lodash][try]:

```js
// @flow
const x: {[string]: number} = {one: 1};
const one: number = x.one;  // sound, in this case
const two: number = x.two;  // unsound! no error!
two.toFixed();  // fails at runtime!
```

[docs]: https://flow.org/en/docs/types/objects/#toc-objects-as-maps
[try]: https://flow.org/try/#0PTAEAEDMBsHsHcBQBjWA7AzgF1ADwFygDeA2tgE4CWaA5gLqFoCuAtgEYCm5AvqALzF0HQgEZuAbhTpsoIY1ady-PADoh40KBCgMsJmgAmAGlDVQWABaUMoZAEMMHKZhxZ4seey7LcKt7A0tMH1dfQMAQlA0WFAuclhycMR-P1gAMUpcDgMACgBKQO1IO0poGzsccn0sShYOJKA

You should read the type `{[V]: T}` as, “an object whose keys are of
type `V` and whose values are of type `T`”.

The result of `keyBy` is an object all of whose values are indeed of
type `T`—the object does not contain any extra `null` or `undefined`
values. If the return type were instead `{[V]: ?T}`, that would suggest
that `keyBy` may return an object with values that are `null` or
`undefined`, but this is not the case.

Note that the same occurs with arrays: if `arr` has type `Foo[]`, then
`arr[999]` will be inferred to have type `Foo`, even if in fact `arr`
may have fewer than 1000 elements and so `arr[999]` could be
`undefined`. Again, this is by design.

**Comment by villesau** [comment] 2018-09-06 20:50
@wchargin has pretty good explanation and IMO the behaviour is more consistent if it's not maybe type. It's already argued couple of times before too.

**Closed by villesau** 2018-09-06 20:50 UTC
