### ISSUE TITLE
Support Yarn Workspaces

### ISSUE THREAD

**Issue by k15a** [flow-typed/flow-typed#1391] opened 2017-10-23 10:09 UTC
Yarn has a feature called [workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) which is quite good for monorepos.

The problem is that they are not working good with flow and flow-typed. There are two options to use flow in a monorepo:

# Use a single flow in the root

The problem is that flow will only use the flow-typed folder in the root so all typings installed in the individual package folders are ignored.

Flow-typed could install all typings into the root and check for the workspaces key in the package.json for individual packages. (This will probably be an issue when package A depends on a different version of an npm package than package B)

# Use one flow per package

The problem here is that yarn will hoist some packages into the root of the project and flow can't find them there. This is a problem with flow because it seems that they use a different module resolution algorithm then node does. https://github.com/facebook/flow/issues/5107

**Comment by Inkdpixels** [comment] 2017-12-20 13:31
@k15a FYI there is a CLI called [flow-mono-cli](https://immoweltgroup.gitbooks.io/flow-mono-cli/) which solves most of the issues when working with flow in a mono-repo. Check it out, if you have any additional feature requests or feedback I am more than happy to hear from you guys! :)

**Comment by k15a** [comment] 2017-12-20 14:24
@Inkdpixels I've already seen that and tried it at work. Unfortunately, it's only working with node 8 and if you use yarn will not even install because of some dependency.

**Comment by Inkdpixels** [comment] 2017-12-21 08:38
@k15a That is unfortunate! We do require Node 8 of course since it is the current LTS and advise anyone to upgrade as soon as possible, but the dependency error sounds a bit weird, can you elaborate what exactly is causing an error there so I can reproduce it / fix it? That would be super cool! Thanks in advance :)

**Comment by AugustinLF** [comment] 2018-01-11 14:55
@Inkdpixels and what suggestion do you have when using a single flow at the root? That's the approach I took, but flow-typed now doesn't know how to install the definitions :/

**Comment by Inkdpixels** [comment] 2018-01-15 11:23
@AugustinLF We embrace having flow setup for each package, while it sounds like overhead in the first place we found that flow just works better, faster and  leads to less headaches if you extract packages from your mono-repo in the future. 

The CLI we built guides you on how to properly set up a mono-repo without much hassle and support's you as much as possible, if you have any feedback we are more than open for suggestions! 

FYI we also support root flow-typed definitions, but, as stated before, we need flow-typed and flow in each package. :-)

**Comment by steelbrain** [comment] 2018-07-05 05:46
This issue can be fixed by https://github.com/facebook/flow/pull/6504

**Comment by rcalabro** [comment] 2018-12-13 16:57
+1

**Comment by samuelbriole** [comment] 2018-12-28 09:03
[flow-mono-cli](https://github.com/ImmoweltGroup/flow-mono-cli) is a good option, but an official support would be better !

Here is small article I wrote on the topic : https://medium.com/inato/how-to-use-flow-in-a-mono-repo-8947d43d50fb 😉

**Comment by 11111000000** [comment] 2020-02-02 01:18
any progress here?

**Comment by jeremyblalock** [comment] 2021-01-04 02:54
@11111000000 this stackoverflow answer might be helpful: https://stackoverflow.com/a/57017179/2150422

> To fix it need update .flowconfig:
> 
> ```
> [include]
> ../../node_modules/
> ```
> 
> FS struct:
> 
> ```
> /project_root
> --/node_modules
> --/packages
> ----/module1
> ------.flowconfig>
> ```

**Comment by AndrewSouthpaw** [comment] 2021-01-22 20:18
Thanks for sharing @jeremyblalock ! If anyone is feeling motivated, I'm sure an addition to the README for this repo would be welcome to explain how to add support for yarn workspaces.

**Comment by Brianzchen** [comment] 2021-11-23 08:05
This seems solved from #4140.

@AndrewSouthpaw or anyone else, do you see any reason to keep this issue open? Are there anymore challenges that should be solved by `flow-typed`? I believe if you choose to run a different `.flowconfig` in each package in a monorepo that has no extra functionality need from `flow-typed`

**Comment by AndrewSouthpaw** [comment] 2021-11-26 18:30
Seems reasonable to me! I think a note in the README would still be a valid addition, but I think this is fine to close. Thanks @Brianzchen!

**Closed by AndrewSouthpaw** 2021-11-26 18:30 UTC
Labels: enhancement, cli
