### ISSUE TITLE
[styled-components@v4] Callable signature missing for StyledComponentType 

### ISSUE THREAD

**Issue by melissafzhang** [flow-typed/flow-typed#3318] opened 2019-05-08 23:07 UTC
I'm using Flow 0.85 and getting issues with styled-components@4.x.x libdef. 

Here's the error I get on line 247:
```
Cannot call styled.div because a callable signature is missing in StyledComponentType [1].

     src/components/AvailableBalance/AvailableBalance.js
     244│   margin: 18px 0 24px;
     245│ `;
     246│
     247│ const Holds = styled.div`
     248│   padding: 6px 0;
     249│   margin: 0 -24px 10px;
     250│ `;
     251│
     252│ const HoldRow = styled(Row)`
     253│   padding: 6px 24px 12px 36px;

     ../types/flow-typed/npm/styled-components_v4.x.x.js
 [1] 152│     div: StyledComponentType<StyledElementType<'div'>>,

```

Thanks!

**Comment by pascalduez** [comment] 2019-05-09 06:16
Duplicate of #3104

**Closed by pascalduez** 2019-05-09 06:16 UTC
