### ISSUE TITLE
Need help with install redux-saga

### ISSUE THREAD

**Issue by Ryskulov** [flow-typed/flow-typed#2872] opened 2018-10-23 06:20 UTC
I am trying to integrate flow with flow-types on react project. and have problem with flow-typed
what I did:
`npm i -g flow-typed`
`flow-typed install -s`
then `flow-typed` downloaded types for libs and if i check `flow status` I have 2 errors

```Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ flow-typed/npm/redux-saga_v0.16.x.js:7:36

Cannot resolve module redux-saga/effects.

      4│ // @flow
      5│
      6│ declare module "redux-saga" {
      7│   import typeof * as _effects from "redux-saga/effects";
      8│   declare export var effects: _effects;
      9│
     10│   declare export interface Channel {

Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ flow-typed/npm/redux-saga_v0.16.x.js:470:10

Cannot resolve module redux-saga.

     467│     SpawnEffect,
     468│     TakeEffect,
     469│     Task
     470│   } from "redux-saga";
     471│
     472│   declare export var take: {
     473│     <P: Pattern>(pattern: P): TakeEffect<P, void, void>,



Found 2 errors
```

"redux-saga": "^0.16.0",

please say to me my mistake

**Comment by dmbrooking** [comment] 2019-01-17 16:19
Did you fix this? If so, can you comment on how you fixed?

**Comment by venkatb4u** [comment] 2019-05-27 07:44
Any update on this?

**Comment by michielmetcake** [comment] 2019-06-04 08:27
Also looking for an update/fix for this

**Comment by Brianzchen** [comment] 2022-01-01 03:49
I can't reproduce this with v0.16.x which is what has this syntax. If there's more issues and a way to reproduce please open a new issue with details, thanks.

**Closed by Brianzchen** 2022-01-01 03:49 UTC
