### ISSUE TITLE
[react-redux_v7.x.x] connect does not work with intersected props

### ISSUE THREAD

**Issue by linlycode** [flow-typed/flow-typed#3477] opened 2019-07-29 09:14 UTC
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

The following code produces errors:

`Cannot call 'connect' because property 'disabled' is missing in 'StateProps' [1] but exists in 'MergeOPSP' [2] in type argument 'MP'.`

```javascript
type OwnProps = {|
    disabled?: boolean,
    path: string,
|}

type StateProps = {|
    user: User,
|}

type Props = OwnProps & StateProps & {
    dispatch: Dispatch<*>,
}

function MyComponent(props: Props) {
    // ...
}

function mapStateToProps({ user }: State): StateProps {
	return { user }
}

connect<Props, OwnProps, StateProps, *, *, *>(mapStateToProps)(MyComponent)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
paste it in [flow try](https://flow.org/try) (could somebody tell me how do I share my flow try?)
``` javascript
// @flow

import React from 'react'

/**************** code from react-redux_v7.x.x.js begin ****************/

declare type Options<S, OP, SP, MP> = {|
    pure?: boolean,
    forwardRef?: boolean,
    areStatesEqual?: (next: S, prev: S) => boolean,
    areOwnPropsEqual?: (next: OP, prev: OP) => boolean,
    areStatePropsEqual?: (next: SP, prev: SP) => boolean,
    areMergedPropsEqual?: (next: MP, prev: MP) => boolean,
    storeKey?: string,
|}

declare class ConnectedComponent<OP, +WC> extends React$Component<OP> {
    static +WrappedComponent: WC;
    getWrappedInstance(): React$ElementRef<WC>;
}

declare type Connector<P, OP, MP: P> = <WC: React$ComponentType<P>>(
    WC,
) => Class<ConnectedComponent<OP, WC>> & WC

declare type MapStateToProps<-S, -OP, +SP> =
    | ((state: S, ownProps: OP) => SP)
    | ((state: S, ownProps: OP) => (state: S, ownProps: OP) => SP)

declare type MergeOPSP<OP, SP, D> = {| ...$Exact<OP>, ...SP, dispatch: D |}

declare function connect<-P, -OP, -SP, -DP, -S, -D>(
    mapStateToProps: MapStateToProps<S, OP, SP>,
    mapDispatchToProps?: null | void,
    mergeProps?: null | void,
    options?: ?Options<S, OP, SP, MergeOPSP<OP, SP, D>>,
): Connector<P, OP, MergeOPSP<OP, SP, D>>

/**************** code from react-redux_v7.x.x.js end ****************/

type Dispatch<A> = (action: A) => A

type User = {
  name: string,
}

type State = {
  user: User,
}

type OwnProps = {|
    disabled?: boolean,
    path: string,
|}

type StateProps = {|
    user: User,
|}

type Props = OwnProps & StateProps & {
//    ...OwnProps, ...StateProps,  // this works, but eslint complains `defaultProp "disabled" has no corresponding propTypes declaration.eslint(react/default-props-match-prop-types)`
    dispatch: Dispatch<*>,
}

function MyComponent(props: Props) {
	const { user } = props
	return (
      <div>{user.name}</div>
    )
}

MyComponent.defaultProps = {
    disabled: false,
}

function mapStateToProps({ user }: State): StateProps {
	return { user }
}

export default connect<Props, OwnProps, StateProps, *, *, *>(mapStateToProps)(MyComponent)
          
export const comp = (
    <MyComponent
      disabled={true}
      path="/"
      user={{ name: "John" }}
      dispatch={(action) => action}
    />
)
```

**What is the expected behavior?**
no error reported

**Local Environment Information**
flow 0.104.0
redux_v4.x.x
react-redux_v7.x.x

**Comment by AndrewSouthpaw** [comment] 2019-07-30 02:59
I'm confused, where are `StateProps` coming from if your component is a _stateless_ functional component?

**Comment by linlycode** [comment] 2019-07-30 07:56
> I'm confused, where are `StateProps` coming from if your component is a _stateless_ functional component?

The "state" in `StateProps` refers to redux store state, not React component state. It's irrelevant to the problem in question.

**Comment by jamesisaac** [comment] 2019-08-06 14:38
You want to be using `...` spread, not `&` intersection.  Especially as you are mixing exact and inexact object types.

Not sure why the default props usage is causing eslint to complain.  But with a functional component there's really no reason to use default props.  From what I understand default props were added as a shorthand for class components, to avoid needing to supply the defaults in every method.  But for functional components you can just add defaults once in the function signature while you're destructuring.

**Comment by LoganBarnett** [comment] 2019-08-06 17:14
Even with the exact spread (`{| ...StateProps, ...DispatchProps |}`) I still run into this problem. Upon inspecting the libdef I found that the merge props is connected to the normal `Props`, but also that the merge props is composed with state, dispatch, and _ownProps_. I think the addition of `ownProps` is in error. The result of `mergeProps` should just be `Props` which is provided directly to the React component. Mixing in `OwnProps` seems wrong. However I am speculating. I want to put together a runtime test to confirm this.

@linlycode in the meantime you can edit your local definition to remove the `MP` type param on `Connector`. From there you'll have to fix all of the `Connector` references to use two params instead of one.

Once the runtime behavior is confirmed to not pass through `OwnProps` I'll look at fixing this.

**Comment by pizza-r0b** [comment] 2019-09-16 22:41
Why is it required to pass the generic types to connect? I'm updating flow in my code base and I have to do this for a lot of different functions many of which are defined in flow-typed (redux saga). Seems to really affect the code base in a negative way if most of the time I need to pass in the type because flow won't infer the type. What's the point of a generic then? Maybe I am missing something.

`connect<Props, OwnProps, StateProps, *, *, *>(mapStateToProps)(MyComponent)`

**Comment by LoganBarnett** [comment] 2019-09-19 15:26
@pizza-r0b There might be better links others can provide, but this [roadmap post](https://medium.com/flow-type/what-the-flow-team-has-been-up-to-54239c62004f) details a lot of changes coming to Flow, and in order to fix some issues where the type coverage is silently lost across module boundaries and inferencing, Flow is instead telling you that it cannot correctly guess the types, and needs you to fill in the gaps.

> What's the point of a generic then? Maybe I am missing something.

Generics and type inferencing are somewhat orthogonal features. Generics (or parameterized types) lets you specify a type or type constraint instead of a fixed type.

When you create an `Array<number>`, it will only let you work with `number`s in that array. But if it's `Array<string>` then you can have your array only allow `string` to be used. But you're still working with `Array<T>` the whole time. No need to duplicate the type when `Array` actually doesn't care what that the element type is.

Type inferencing just lets the type system make guesses about what the type of a thing must be. When it sees `const x = 'foo'` it knows that `x` is a `string` because `x` cannot be reassigned, and has been assigned the `string` of `'foo'`. If you used `let x = 'foo'; x = 5`, Flow would accept that and (perhaps to your dismay) allow this `number` assignment. Here it has inferred that `x` is `string | number`.

I agree the new `connect` type parameters you must declare are a bit onerous, but when doing the switch I've already found and corrected mistakes because of that silent loss of type coverage I mentioned earlier. I'd rather type a little more and avoid potential bugs :)

**Comment by LoganBarnett** [comment] 2019-10-08 04:20
To followup on my own post: I found that both `dispatch` and `OwnProps` are indeed chained through by the default `mergeProps`, all according to the `react-redux` documentation. Per @jamesisaac the `&` does not work regarding exact objects and instead the spread (`...`) must be used. I do not understand how these differ in any practical sense but have found tickets that verify this is the case when trying to use product types with exact types.

**Comment by AndrewSouthpaw** [comment] 2019-10-14 22:17
Calling this closed. Thanks all for the research!

**Closed by AndrewSouthpaw** 2019-10-14 22:17 UTC
